### PR TITLE
Run tests serially to improve test times on the CI

### PR DESCRIPTION
**Pull request by jrchatruc**

### CODE REVIEW

**Comment by igamigo** [comment]
🤞

**Comment by facundoolano** [comment]
is this working? the test task in CI seems to be runnning from since 10+ mins ago

**Comment by jrchatruc** [comment]
> is this working? the test task in CI seems to be runnning from since 10+ mins ago

I'm not sure, the ones in other PRs are taking 2+ hours so i'm waiting to see how long they all take

**Comment by igamigo** [comment]
Free github runners are considerably slower and less reliable.

**Comment by facundoolano** [comment]
I _think_ this shouldn't be necessary anymore after going back to self hosted runners

**Comment by jrchatruc** [comment]
> I _think_ this shouldn't be necessary anymore after going back to self hosted runners

Yep, closing it

**Pull request closed without merging**
