### PR TITLE
Remove shared state references and locks and fix CI

### PR DESCRIPTION
**Pull request by igamigo**
As a consequence of the changes to use channels to process incoming messages, there is no more necessity to share state between cloned Node objects, so this PR removes all shared state.

This PR also adds a couple of dependencies in the CI in order to get `cargo test` working correctly.

### CODE REVIEW

**Comment by igamigo** [comment]
[Finish lock-commit implementation](https://trello.com/c/tBY9yrc1/48-finish-lock-commit-implementation)

**Comment by facundoolano** [comment]
you have a couple of conflicts here, also pull from main to update the diff

**Comment by igamigo** [comment]
Rebased and resolve conflicts caused after the base branch went into main

**Review by facundoolano — APPROVED** [review]
nice

**Pull request merged**
